version: "3.8"
services:
  dev-postgres:
    image: postgres:14.7-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - lesson
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  lesson: